from ROOT import *

fin0  = TFile.Open("../EWK_LLJJ_mu_QCDScalenom_JESnom_v25_bdt_alldata4_qglweightsnorm_vetoeff_newGapAct_reminiaod.root")
#hist0 = fin0.Get("hbdt_atanh")
hist0 = fin0.Get("hbdt")
#hist0.Scale(1./hist0.Integral())
hist0.Scale(36000.)
hist0.SetLineColor(kRed)
#hist0.GetYaxis().SetTitle("Normalized Yield")
hist0.GetYaxis().SetTitle("Yield per 36 fb^{-1}")
hist0.GetYaxis().SetTitleOffset(1.8)
hist0.GetYaxis().SetTitleSize(.04)
hist0.SetStats(kFALSE)
#fin1  = TFile.Open("../EWK_LLJJ_aTGC_mu_QCDScalenom_JESnom_v25_aTGC_qgl_SM.root")
fin1  = TFile.Open("../EWK_LLJJ_aTGC_full_mu_QCDScalenom_JESnom_v25_aTGC_new_qglnorm.root")
#hist1 = fin1.Get("hbdt_atanh")
hist1 = fin1.Get("hbdt")
#hist1.Scale(1./hist1.Integral())
hist1.Scale(36000.)
hist1.SetLineColor(kGreen)

leg  = TLegend(0.4,0.75,0.6,0.85)
leg.SetFillStyle(-1)
leg.SetBorderSize(0)
leg.SetTextFont(42)
leg.AddEntry(hist0,"Dimuon","")
#leg.AddEntry(hist0,"Dielectron","")
leg.AddEntry(hist0,"EWK LLJJ","PL")
leg.AddEntry(hist1,"aTGC, SM point","PL")

gStyle.SetPadLeftMargin(0.15)

c0 = TCanvas("c0","",600,600)

right,top   = gStyle.GetPadRightMargin(),gStyle.GetPadTopMargin()
left,bottom = gStyle.GetPadLeftMargin(),gStyle.GetPadBottomMargin()
pCMS1 = TPaveText(left,1.-top,0.4,1.,"NDC")
pCMS1.SetTextFont(62)
pCMS1.SetTextSize(top*0.75)
pCMS1.SetTextAlign(12)
pCMS1.SetFillStyle(-1)
pCMS1.SetBorderSize(0)
pCMS1.AddText("CMS")

pCMS12 = TPaveText(left+0.1,1.-top*1.13,0.57,1.,"NDC")
pCMS12.SetTextFont(52)
pCMS12.SetTextSize(0.04)
pCMS12.SetTextAlign(12)
pCMS12.SetFillStyle(-1)
pCMS12.SetBorderSize(0)
pCMS12.AddText("Dimuon")


pCMS2 = TPaveText(0.5,1.-top,1.-right*0.5,1.,"NDC")
pCMS2.SetTextFont(42)
pCMS2.SetTextSize(top*0.55)
pCMS2.SetTextAlign(32)
pCMS2.SetFillStyle(-1)
pCMS2.SetBorderSize(0)
pCMS2.AddText("13 TeV")


hist0.Draw()
hist1.Draw("same")
hist0.Draw("same")
leg.Draw()
#pCMS1.Draw()
#pCMS2.Draw()
#pCMS12.Draw()
#c0.SaveAs("el_atahn_norm.png")
#c0.SaveAs("mu_atahn_norm.png")
#c0.SaveAs("mu_atahn.png")
#c0.SaveAs("mu_bdt.png")
#c0.SaveAs("el_bdt_norm.png")
c0.SaveAs("mu_bdt_norm.png")


